#Keybindings

#remap prefix key 
unbind C-b
set-option -g prefix C-a

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

#allow mouse
set -g mouse on

#easier sourcing
unbind r
bind r source-file ~/.tmux.conf

#change zoom action to m
bind -r m resize-pane -Z

#Plugins

#plugin manager
set -g @plugin 'tmux-plugins/tpm'

#easy navigation like vim 
set -g @plugin 'christoomey/vim-tmux-navigator'

#Design Changes
set -g default-terminal "screen-256color"


#init tmux plugin manager (Keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
